# Generated by Django 4.2.6 on 2023-11-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscribed',
            field=models.BooleanField(default=True, verbose_name='Подписка'),
        ),
    ]
